services:
  - type: web
    name: ptt-btp
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --workers 2 --timeout 120
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        sync: false          # à saisir manuellement dans le dashboard Render
      - key: DATABASE_URL
        sync: false
      - key: R2_ENDPOINT
        sync: false
      - key: R2_BUCKET
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
